CREATE TABLE "user"
(
    user_id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username          VARCHAR(255),
    email             VARCHAR(255),
    role              VARCHAR(255),
    password          VARCHAR(255),
    first_name        VARCHAR(255),
    last_name         VARCHAR(255),
    birth_date        date,
    phone_number      VARCHAR(255),
    address           VARCHAR(255),
    registration_date date,
    last_login_date   date,
    CONSTRAINT pk_user PRIMARY KEY (user_id)
);

CREATE TABLE password_reset_request
(
    request_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT,
    reset_token     VARCHAR(255),
    expiration_date date,
    CONSTRAINT pk_password_reset_request PRIMARY KEY (request_id)
);

CREATE TABLE user_session
(
    user_session_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT,
    session_token   VARCHAR(255),
    expiration_date date,
    CONSTRAINT pk_user_session PRIMARY KEY (user_session_id)
);

CREATE TABLE user_token
(
    user_token_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT,
    token           VARCHAR(255),
    expiration_date date,
    CONSTRAINT pk_user_token PRIMARY KEY (user_token_id)
);